export const productOptions = {
  IFPD: {
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch"],
    specs: [
      "Android 9, 4GB RAM, 32GB ROM",
      "Android 8, 4GB RAM, 32GB ROM",
      "Android 11, 4GB RAM, 32GB ROM",
      "Android 11, 8GB RAM, 128GB ROM",
      "Android 13, 4GB RAM, 32GB ROM",
      "Android 13, 8GB RAM, 128GB ROM",
      "Android 13, 8GB RAM, 128GB ROM  Inbuilt Camera",
      "Android 14, 8GB RAM, 128GB ROM",
      "Android 14, 8GB RAM, 128GB ROM Inbuilt Camera",
    ],
  },
  OPS: {
    sizes: ["N/A"],
    specs: [
      // i5 6th Gen
      "i5 6th Gen, 8GB RAM, 256GB ROM",
      "i5 6th Gen, 8GB RAM, 512GB ROM",
      "i5 6th Gen, 8GB RAM, 1TB ROM",
      "i5 6th Gen, 16GB RAM, 256GB ROM",
      "i5 6th Gen, 16GB RAM, 512GB ROM",
      "i5 6th Gen, 16GB RAM, 1TB ROM",

      // i5 7th Gen
      "i5 7th Gen, 8GB RAM, 256GB ROM",
      "i5 7th Gen, 8GB RAM, 512GB ROM",
      "i5 7th Gen, 8GB RAM, 1TB ROM",
      "i5 7th Gen, 16GB RAM, 256GB ROM",
      "i5 7th Gen, 16GB RAM, 512GB ROM",
      "i5 7th Gen, 16GB RAM, 1TB ROM",

      // i5 8th Gen
      "i5 8th Gen, 8GB RAM, 256GB ROM",
      "i5 8th Gen, 8GB RAM, 512GB ROM",
      "i5 8th Gen, 8GB RAM, 1TB ROM",
      "i5 8th Gen, 16GB RAM, 256GB ROM",
      "i5 8th Gen, 16GB RAM, 512GB ROM",
      "i5 8th Gen, 16GB RAM, 1TB ROM",

      // i5 11th Gen
      "i5 11th Gen, 8GB RAM, 256GB ROM",
      "i5 11th Gen, 8GB RAM, 512GB ROM",
      "i5 11th Gen, 8GB RAM, 1TB ROM",
      "i5 11th Gen, 16GB RAM, 256GB ROM",
      "i5 11th Gen, 16GB RAM, 512GB ROM",
      "i5 11th Gen, 16GB RAM, 1TB ROM",

      // i5 12th Gen
      "i5 12th Gen, 8GB RAM, 256GB ROM",
      "i5 12th Gen, 8GB RAM, 512GB ROM",
      "i5 12th Gen, 8GB RAM, 1TB ROM",
      "i5 12th Gen, 16GB RAM, 256GB ROM",
      "i5 12th Gen, 16GB RAM, 512GB ROM",
      "i5 12th Gen, 16GB RAM, 1TB ROM",

      // i7 4th Gen
      "i7 4th Gen, 8GB RAM, 256GB ROM",
      "i7 4th Gen, 8GB RAM, 512GB ROM",
      "i7 4th Gen, 8GB RAM, 1TB ROM",
      "i7 4th Gen, 16GB RAM, 256GB ROM",
      "i7 4th Gen, 16GB RAM, 512GB ROM",
      "i7 4th Gen, 16GB RAM, 1TB ROM",

      // i7 5th Gen
      "i7 5th Gen, 8GB RAM, 256GB ROM",
      "i7 5th Gen, 8GB RAM, 512GB ROM",
      "i7 5th Gen, 8GB RAM, 1TB ROM",
      "i7 5th Gen, 16GB RAM, 256GB ROM",
      "i7 5th Gen, 16GB RAM, 512GB ROM",
      "i7 5th Gen, 16GB RAM, 1TB ROM",

      // i7 6th Gen
      "i7 6th Gen, 8GB RAM, 256GB ROM",
      "i7 6th Gen, 8GB RAM, 512GB ROM",
      "i7 6th Gen, 8GB RAM, 1TB ROM",
      "i7 6th Gen, 16GB RAM, 256GB ROM",
      "i7 6th Gen, 16GB RAM, 512GB ROM",
      "i7 6th Gen, 16GB RAM, 1TB ROM",

      // i7 7th Gen
      "i7 7th Gen, 8GB RAM, 256GB ROM",
      "i7 7th Gen, 8GB RAM, 512GB ROM",
      "i7 7th Gen, 8GB RAM, 1TB ROM",
      "i7 7th Gen, 16GB RAM, 256GB ROM",
      "i7 7th Gen, 16GB RAM, 512GB ROM",
      "i7 7th Gen, 16GB RAM, 1TB ROM",

      // i7 8th Gen
      "i7 8th Gen, 8GB RAM, 256GB ROM",
      "i7 8th Gen, 8GB RAM, 512GB ROM",
      "i7 8th Gen, 8GB RAM, 1TB ROM",
      "i7 8th Gen, 16GB RAM, 256GB ROM",
      "i7 8th Gen, 16GB RAM, 512GB ROM",
      "i7 8th Gen, 16GB RAM, 1TB ROM",

      // i7 9th Gen
      "i7 9th Gen, 8GB RAM, 256GB ROM",
      "i7 9th Gen, 8GB RAM, 512GB ROM",
      "i7 9th Gen, 8GB RAM, 1TB ROM",
      "i7 9th Gen, 16GB RAM, 256GB ROM",
      "i7 9th Gen, 16GB RAM, 512GB ROM",
      "i7 9th Gen, 16GB RAM, 1TB ROM",

      // i7 10th Gen
      "i7 10th Gen, 8GB RAM, 256GB ROM",
      "i7 10th Gen, 8GB RAM, 512GB ROM",
      "i7 10th Gen, 8GB RAM, 1TB ROM",
      "i7 10th Gen, 16GB RAM, 256GB ROM",
      "i7 10th Gen, 16GB RAM, 512GB ROM",
      "i7 10th Gen, 16GB RAM, 1TB ROM",

      // i7 11th Gen
      "i7 11th Gen, 8GB RAM, 256GB ROM",
      "i7 11th Gen, 8GB RAM, 512GB ROM",
      "i7 11th Gen, 8GB RAM, 1TB ROM",
      "i7 11th Gen, 16GB RAM, 256GB ROM",
      "i7 11th Gen, 16GB RAM, 512GB ROM",
      "i7 11th Gen, 16GB RAM, 1TB ROM",

      // i7 12th Gen
      "i7 12th Gen, 8GB RAM, 256GB ROM",
      "i7 12th Gen, 8GB RAM, 512GB ROM",
      "i7 12th Gen, 8GB RAM, 1TB ROM",
      "i7 12th Gen, 16GB RAM, 256GB ROM",
      "i7 12th Gen, 16GB RAM, 512GB ROM",
      "i7 12th Gen, 16GB RAM, 1TB ROM",
    ],
  },

  "Digital Podium": {
    sizes: ["Standard"],
    specs: [
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 2 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
    ],
  },
  "Advance Digital Podium": {
    sizes: ["Front Display 32inch"],
    specs: [
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 2 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
    ],
  },
  "Audio Podium": { sizes: ["Full"], specs: ["N/A"] },
  Kiosk: {
    sizes: ["32 inch,43 inch,55 inch,65 inch"],
    specs: ["Touch Andriod 13/4/32", "Non-Touch Andriod 13/4/32"],
  },
  "PTZ Camera": {
    sizes: ["N/A"],
    specs: [
      "Non-Voice Tracking-Full HD",
      "UHD 20x",
      "FHD Voice Tracking",
      "4K Auto Tracking",
      "4K 12x",
      "HD 20x",
    ],
  },
  "Document Camera": {
    sizes: ["N/A"],
    specs: [
      "Hydraulic Wall Mount Visualizer",
      "Non-Hydraulic Wall Mount Visualizer",
      "Slim Portable Visualizer",
      "Table Top Portable Visualizer",
      "Visualizer",
    ],
  },
  UPS: {
    sizes: ["Standard"],
    specs: [
      "1 KVA",
      "2 KVA",
      "3 KVA",
      "4 KVA",
      "5 KVA",
      "6 KVA",
      "7 KVA",
      "8 KVA",
      "9 KVA",
      "10 KVA",
      "Offline UPS",
      "Online UPS",
    ],
  },
  "Wallmount Kit": {
    sizes: ["55 inch", "65 inch", "75 inch", "86 inch", "98 inch"],
    specs: ["Standard"],
  },
  "Stylus Pen": { sizes: ["N/A"], specs: ["N/A"] },
  "Sliding Shutter": {
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch"],
    specs: [
      "Common",
      "White & Red Dispaly Boards",
      "White & Green Dispaly Boards",
      "White & Blue Dispaly Boards",
      "N/A",
    ],
  },
  "3 Cup Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  Microphone: {
    sizes: ["N/A"],
    specs: ["Handheld Collar Mic", "Goose Neck Mic", "Collar/Lapel Mic"],
  },
  Keyboard: {
    sizes: ["N/A"],
    specs: ["Wireless", "Wired"],
  },
  "LED Display Controller": {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  "Aluminium Profile Frame for LED Display": {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  Mouse: {
    sizes: ["N/A"],
    specs: ["Wireless", "Wired"],
  },
  "Interactive White Board": {
    sizes: ["82 inch"],
    specs: ["Ceramic", "Non-Ceramic"],
  },
  "Floor Stand": { sizes: ["N/A"], specs: ["N/A"] },
  "Notice Board": { sizes: ["N/A"], specs: ["N/A"] },
  Visualizer: { sizes: ["N/A"], specs: ["N/A"] },
  "Web Cam": {
    sizes: ["N/A"],
    specs: ["Full HD Non-AI Featured", "4K AI Featured", "4K Auto Tracking"],
  },
  "Bluetooth Microphone": { sizes: ["N/A"], specs: ["N/A"] },
  "UPS Cabinet": { sizes: ["N/A"], specs: ["N/A"] },
  "SD Card": {
    sizes: ["N/A"],
    specs: ["8GB", "16GB", "32GB", "64GB", "128GB"],
  },
  Casing: { sizes: ["N/A"], specs: ["N/A"] },
  "Fitting Accessories": { sizes: ["N/A"], specs: ["N/A"] },
  "HDMI Cable": {
    sizes: ["N/A"],
    specs: ["Standard", "4K"],
  },
  "White Board": {
    sizes: ["2x3", "3x4", "4x6", "4x5", "4x8", "4x10"],
    specs: ["Non-Magnetic", "Magnetic", "RC Magnetic", "UM", "UG"],
  },
  "C-type Cable": { sizes: ["N/A"], specs: ["N/A"] },
  "Fujifilm-Printer": {
    sizes: ["N/A"],
    specs: [
      "Color Printer",
      "Monochrome Printer",
      "Black and White Printer",
      "Multifunction Color Printer",
      "Multifunction Monochrome Printer",
      "Multifunction Black and White Printer",
    ],
  },
  "Google TV": {
    sizes: ["43 inch", "50 inch", "55 inch"],
    specs: ["4GB RAM / 32GB ROM 4K"],
  },
  "Wriety Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Ceiling Mount Kit": {
    sizes: ["Standard"],
    specs: ["Projector Ceiling Mount", "PTZ Ceiling Mount"],
  },
  "Almirah Type Shutter": {
    sizes: ["65 inch", "75 inch", "86 inch", "98  inch"],
    specs: ["Plain", "White Boards", "Green Boards"],
  },
  Aicharya: {
    sizes: ["N/A"],
    specs: ["Standard"],
  },
  TripodStand: {
    sizes: ["N/A"],
    specs: ["Standard"],
  },
  Logo: { sizes: ["N/A"], specs: ["N/A"] },
  Microphones: { sizes: ["N/A"], specs: ["N/A"] },
  "E-Share License": { sizes: ["N/A"], specs: ["N/A"] },
  "PRO Share Software": { sizes: ["N/A"], specs: ["N/A"] },
  "E Share Software": { sizes: ["N/A"], specs: ["N/A"] },
  "DMS Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Battery Bank": { sizes: ["N/A"], specs: ["N/A"] },
  "Rack & Interlink": { sizes: ["N/A"], specs: ["N/A"] },
  "Green Board": {
    sizes: ["2x3", "3x4", "4x6", "4x5", "4x8", "4x10"],
    specs: ["Non-Magnetic", "Magnetic", "RC Magnetic", "UM", "UG"],
  },
  "Wooden Podium": { sizes: ["N/A"], specs: ["N/A"] },
  "Writing Board": { sizes: ["N/A"], specs: ["N/A"] },
  "LED Video Wall": { sizes: ["N/A"], specs: ["N/A"] },
  "4K Video Bar": { sizes: ["N/A"], specs: ["N/A"] },
  "Microsoft Office 2016 Licensed": { sizes: ["N/A"], specs: ["N/A"] },
  "Windows 11 Licensed": { sizes: ["N/A"], specs: ["N/A"] },
  "Embibe Content": { sizes: ["N/A"], specs: ["N/A"] },
  SSD: {
    sizes: ["N/A"],
    specs: ["256GB", "512GB", "1TB"],
  },
  RAM: {
    sizes: ["N/A"],
    specs: ["8GB", "16GB"],
  },
  "Video Conferencing Camera": { sizes: ["N/A"], specs: ["N/A"] },
  "CBSE Content": { sizes: ["N/A"], specs: ["N/A"] },
  "ICSE Content": { sizes: ["N/A"], specs: ["N/A"] },
  "PA System Speakers": { sizes: ["N/A"], specs: ["N/A"] },
  "Red Board": { sizes: ["N/A"], specs: ["N/A"] },
  "Promark Stickers": { sizes: ["N/A"], specs: ["N/A"] },
  "Bluetooth Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  "3 Cup Conference Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  "Conference Setup-Delegate Room": { sizes: ["N/A"], specs: ["N/A"] },
  Content: { sizes: ["N/A"], specs: ["N/A"] },
  Flex: { sizes: ["N/A"], specs: ["N/A"] },
  "Wireless Speakerphone - Two Pair": { sizes: ["N/A"], specs: ["N/A"] },
  Remote: { sizes: ["N/A"], specs: ["N/A"] },
  "Educational Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Hydraulic Bracket": { sizes: ["N/A"], specs: ["N/A"] },
  "Desktop PC Monitor": { sizes: ["N/A"], specs: ["N/A"] },
  "Home Theatre": { sizes: ["N/A"], specs: ["N/A"] },
  "Digital Audio Processor": { sizes: ["N/A"], specs: ["N/A"] },
  Projector: {
    sizes: ["N/A"],
    specs: ["Long Throw", "Short Throw", "Ultra Long Throw"],
  },
  "LED TV": { sizes: ["N/A"], specs: ["N/A"] },
  "Digital Podium Controller": { sizes: ["N/A"], specs: ["N/A"] },
  "Amplifier Mic Receiver": { sizes: ["N/A"], specs: ["N/A"] },
  "Wireless Mic Receiver": { sizes: ["N/A"], specs: ["N/A"] },
  "Projector Screen": { sizes: ["N/A"], specs: ["N/A"] },
  Speakerphone: { sizes: ["N/A"], specs: ["N/A"] },

  "Bubble Roll": { sizes: ["N/A"], specs: ["N/A"] },
  "Wrapping Roll": { sizes: ["N/A"], specs: ["N/A"] },
};

export const statesAndCities = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Jaganathpuram",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Kurnool",
    "Rajahmundry",
    "Nellore",
    "Anantapur",
    "Kadapa",
    "Srikakulam",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Proddatur",
    "Machilipatnam",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Tawang",
    "Ziro",
    "Pasighat",
    "Bomdila",
    "Naharlagun",
    "Roing",
    "Aalo",
    "Tezu",
    "Changlang",
    "Khonsa",
    "Yingkiong",
    "Daporijo",
    "Seppa",
  ],
  Assam: [
    "Agartala",
    "Tripura",
    "Guwahati",
    "Dibrugarh",
    "Jorhat",
    "Silchar",
    "Tezpur",
    "Tinsukia",
    "Nagaon",
    "Sivasagar",
    "Barpeta",
    "Goalpara",
    "Karimganj",
    "Lakhimpur",
    "Diphu",
    "Golaghat",
    "Kamrup",
  ],
  Bihar: [
    "Patna",
    "Mirzapur",
    "Jehanabad",
    "Mithapur",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Ara",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chapra",
    "Sasaram",
    "Hajipur",
    "Bihar Sharif",
    "Sitamarhi",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Korba",
    "Bhilai",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Dhamtari",
    "Kawardha",
    "Mahasamund",
    "Kondagaon",
    "Bijapur",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Sanguem",
    "Canacona",
    "Quepem",
    "Valpoi",
    "Sanquelim",
    "Curchorem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Morbi",
    "Nadiad",
    "Porbandar",
    "Mehsana",
    "Bharuch",
    "Navsari",
    "Surendranagar",
  ],
  Haryana: [
    "Bahadurgarh",
    "Charkhi Dadri",
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Hisar",
    "Rohtak",
    "Karnal",
    "Bhiwani",
    "Kaithal",
    "Kurukshetra",
    "Sonipat",
    "Jhajjar",
    "Jind",
    "Fatehabad",
    "Pehowa",
    "Pinjore",
    "Rewari",
    "Yamunanagar",
    "Sirsa",
    "Dabwali",
    "Narwana",
  ],
  "Himachal Pradesh": [
    "Nagrota Surian",
    "Shimla",
    "Dharamshala",
    "Solan",
    "Mandi",
    "Hamirpur",
    "Kullu",
    "Manali",
    "Nahan",
    "Palampur",
    "Baddi",
    "Sundarnagar",
    "Paonta Sahib",
    "Bilaspur",
    "Chamba",
    "Una",
    "Kangra",
    "Parwanoo",
    "Nalagarh",
    "Rohru",
    "Keylong",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Palamu",
    "Gumla",
    "Lohardaga",
    "Dumka",
    "Chatra",
    "Pakur",
    "Jamtara",
    "Simdega",
    "Sahibganj",
    "Godda",
    "Latehar",
    "Khunti",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Kalaburagi",
    "Ballari",
    "Davangere",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Vijayapura",
    "Chikkamagaluru",
    "Hassan",
    "Mandya",
    "Raichur",
    "Bidar",
    "Bagalkot",
    "Chitradurga",
    "Kolar",
    "Gadag",
    "Yadgir",
    "Haveri",
    "Dharwad",
    "Ramanagara",
    "Chikkaballapur",
    "Kodagu",
    "Koppal",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kannur",
    "Alappuzha",
    "Thrissur",
    "Kottayam",
    "Palakkad",
    "Ernakulam",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Kollam",
    "Kasaragod",
    "Punalur",
    "Varkala",
    "Changanassery",
    "Kayani",
    "Kizhakkambalam",
    "Perumbavoor",
    "Muvattupuzha",
    "Attingal",
    "Vypin",
    "North Paravur",
    "Adoor",
    "Cherthala",
    "Mattancherry",
    "Fort Kochi",
    "Munroe Island",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Ratlam",
    "Satna",
    "Dewas",
    "Murwara (Katni)",
    "Chhindwara",
    "Rewa",
    "Burhanpur",
    "Khandwa",
    "Bhind",
    "Shivpuri",
    "Vidisha",
    "Sehore",
    "Hoshangabad",
    "Itarsi",
    "Neemuch",
    "Chhatarpur",
    "Betul",
    "Mandsaur",
    "Damoh",
    "Singrauli",
    "Guna",
    "Ashok Nagar",
    "Datia",
    "Mhow",
    "Pithampur",
    "Shahdol",
    "Seoni",
    "Mandla",
    "Tikamgarh",
    "Raisen",
    "Narsinghpur",
    "Morena",
    "Barwani",
    "Rajgarh",
    "Khargone",
    "Anuppur",
    "Umaria",
    "Dindori",
    "Sheopur",
    "Alirajpur",
    "Jhabua",
    "Sidhi",
    "Harda",
    "Balaghat",
    "Agar Malwa",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Thane",
    "Satara",
    "Latur",
    "Chandrapur",
    "Jalgaon",
    "Bhiwandi",
    "Shirdi",
    "Akola",
    "Parbhani",
    "Raigad",
    "Washim",
    "Buldhana",
    "Nanded",
    "Yavatmal",
    "Beed",
    "Amravati",
    "Kalyan",
    "Dombivli",
    "Ulhasnagar",
    "Nagothane",
    "Vasai",
    "Virar",
    "Mira-Bhayandar",
    "Dhule",
    "Sangli",
    "Wardha",
    "Ahmednagar",
    "Pandharpur",
    "Malegaon",
    "Osmanabad",
    "Gondia",
    "Baramati",
    "Jalna",
    "Hingoli",
    "Sindhudurg",
    "Ratnagiri",
    "Palghar",
    "Ambarnath",
    "Badlapur",
    "Taloja",
    "Alibaug",
    "Murbad",
    "Karjat",
    "Pen",
    "Newasa",
  ],
  Manipur: [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Bishnupur",
    "Kakching",
    "Senapati",
    "Ukhrul",
    "Tamenglong",
    "Jiribam",
    "Moreh",
    "Noney",
    "Pherzawl",
    "Kangpokpi",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Cherrapunjee",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Mawkyrwat",
    "Resubelpara",
    "Mairang",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Saiha",
    "Lawngtlai",
    "Mamit",
    "Hnahthial",
    "Khawzawl",
    "Saitual",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Mon",
    "Zunheboto",
    "Phek",
    "Longleng",
    "Kiphire",
    "Peren",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Puri",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Jeypore",
    "Angul",
    "Dhenkanal",
    "Keonjhar",
    "Kendrapara",
    "Jagatsinghpur",
    "Paradeep",
    "Bargarh",
    "Rayagada",
    "Koraput",
    "Nabarangpur",
    "Kalahandi",
    "Nuapada",
    "Phulbani",
    "Balangir",
    "Sundargarh",
  ],
  Punjab: [
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Nabha",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Gurdaspur",
    "Ferozepur",
    "Sangrur",
    "Moga",
    "Rupnagar",
    "Kapurthala",
    "Faridkot",
    "Muktsar",
    "Fazilka",
    "Barnala",
    "Mansa",
    "Tarn Taran",
    "Nawanshahr",
    "Pathankot",
    "Zirakpur",
    "Khanna",
    "Malerkotla",
    "Abohar",
    "Rajpura",
    "Phagwara",
    "Batala",
    "Samrala",
    "Anandpur Sahib",
    "Sirhind",
    "Kharar",
    "Morinda",
    "Bassi Pathana",
    "Khamanon",
    "Chunni Kalan",
    "Balachaur",
    "Dinanagar",
    "Dasuya",
    "Nakodar",
    "Jagraon",
    "Sunam",
    "Dhuri",
    "Lehragaga",
    "Rampura Phul",
  ],
  Rajasthan: [
    "Baran",
    "Newai",
    "Gaganagar",
    "Suratgarh",
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Kota",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Nagaur",
    "Jhunjhunu",
    "Chittorgarh",
    "Tonk",
    "Barmer",
    "Jaisalmer",
    "Dholpur",
    "Bhilwara",
    "Hanumangarh",
    "Sawai Madhopur",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Pelling",
    "Geyzing",
    "Mangan",
    "Rangpo",
    "Jorethang",
    "Yuksom",
    "Ravangla",
    "Lachen",
    "Lachung",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thanjavur",
    "Tuticorin",
    "Dindigul",
    "Cuddalore",
    "Kancheepuram",
    "Nagercoil",
    "Kumbakonam",
    "Karur",
    "Sivakasi",
    "Namakkal",
    "Tiruppur",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Ramagundam",
    "Siddipet",
    "Adilabad",
    "Nalgonda",
    "Mancherial",
    "Kothagudem",
    "Zaheerabad",
    "Miryalaguda",
    "Bhongir",
    "Jagtial",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Kamalpur",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Sonamura",
    "Melaghar",
  ],
  "Uttar Pradesh": [
    "Shikohabad",
    "Baghpat",
    "Mahuwadabar",
    "Anandnagar Maharajganj",
    "Badhnan",
    "Khalilabad",
    "Lucknow",
    "Matbarganj",
    "Kasganj",
    "Kanpur",
    "Varanasi",
    "Agra",
    "Prayagraj (Allahabad)",
    "Ghaziabad",
    "Noida",
    "Meerut",
    "Aligarh",
    "Bareilly",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura-Vrindavan",
    "Budaun",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad-Fatehgarh",
    "Ayodhya",
    "Unnao",
    "Jaunpur",
    "Lakhimpur",
    "Hathras",
    "Banda",
    "Pilibhit",
    "Barabanki",
    "Khurja",
    "Gonda",
    "Mainpuri",
    "Lalitpur",
    "Sitapur",
    "Etah",
    "Deoria",
    "Ghazipur",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Rishikesh",
    "Mussoorie",
    "Almora",
    "Pithoragarh",
    "Haldwani",
    "Rudrapur",
    "Bageshwar",
    "Champawat",
    "Uttarkashi",
    "Roorkee",
    "Tehri",
    "Lansdowne",
  ],
  "West Bengal": [
    "Kolkata",
    "Garia",
    "Darjeeling",
    "Siliguri",
    "Howrah",
    "Asansol",
    "Durgapur",
    "Malda",
    "Cooch Behar",
    "Haldia",
    "Kharagpur",
    "Raiganj",
    "Bardhaman",
    "Jalpaiguri",
    "Chandannagar",
    "Kalimpong",
    "Alipurduar",
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Havelock Island",
    "Diglipur",
    "Neil Island",
    "Car Nicobar",
    "Little Andaman",
    "Long Island",
    "Mayabunder",
    "Campbell Bay",
    "Rangat",
    "Wandoor",
  ],
  Chandigarh: [
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 7",
    "Sector 8",
    "Sector 9",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Amli",
    "Kachigam",
    "Naroli",
    "Vapi",
    "Marwad",
    "Samarvarni",
    "Kawant",
  ],
  Delhi: [
    "New Delhi",
    "Rani Bagh",
    "Shalimar Bagh",
    "Tilak Nagar",
    "Hari Nagar Dadb",
    "Hari Nagar",
    "Maya Puri",
    "Alaknanda",
    "Old Delhi",
    "Dwarka",
    "Rohini",
    "Karol Bagh",
    "Lajpat Nagar",
    "Saket",
    "Vasant Kunj",
    "Janakpuri",
    "Mayur Vihar",
    "Shahdara",
    "Preet Vihar",
    "Pitampura",
    "Chanakyapuri",
    "Narela",
    "Mehrauli",
    "Najafgarh",
    "Okhla",
    "Tilak Nagar",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],
  Ladakh: [
    "Leh",
    "Kargil",
    "Diskit",
    "Padum",
    "Nubra",
    "Tangtse",
    "Sankoo",
    "Zanskar",
    "Nyoma",
    "Turtuk",
    "Hanle",
  ],
  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Amini",
    "Andrott",
    "Kalpeni",
    "Kadmat",
    "Chetlat",
    "Bitra",
    "Bangaram",
  ],
  Puducherry: [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam",
    "Villianur",
    "Bahour",
    "Oulgaret",
    "Ariyankuppam",
    "Nettapakkam",
  ],
};

export const orderTypeOptions = [
  "B2G",
  "B2C",
  "B2B",
  "Demo",
  "Replacement",
  "Stock Out",
];
export const companyOptions = ["Promark", "Foxmate", "Promine", "Primus"];

export const paymentMethodOptions = ["Cash", "NEFT", "RTGS", "Cheque"];
export const paymentTermsOptions = [
  "100% Advance",
  "Partial Advance",
  "Credit",
];
export const salesPersonlist = [
  "Aasim Musadiq",
  "Abhay Pratap Singh",
  "Abhay Bhardwaj",
  "Abhayjit Sekhon",
  "Ajay Kumar",
  "Amarjeet Singh",
  "Aniket Singh",
  "Anil Kumar",
  "Animesh Trivedi",
  "Anirban Syam",
  "Ankit Sharma",
  "Anup Panday",
  "Arif Khan",
  "Arwinder Singh",
  "Ashwani Kumar",
  "Awadesh Kumar Srivastav",
  "Bachan Pal",
  "Barjesh Singh",
  "Ekant Yati",
  "Gursewak Singh",
  "Harish Kumar",
  "Heera Singh Daspa",
  "Harpeet Singh",
  "J P Sharma",
  "Jagan Lal",
  "Javvad Akram",
  "Kulwinder Singh",
  "Manish CS Lange",
  "Manjit Singh Chowhan",
  "Mayank Goutam",
  "Mayank Prasad",
  "Nikhil Sharma",
  "Parmjeet Singh",
  "Pitamber Sharma",
  "Priya Sharma",
  "PS Brar",
  "Purnendu Kumar",
  "Raj Bahadur Singh",
  "Rajeev Kanda",
  "Rajeev Kumar Singh",
  "Rajeev Pal Singh",
  "Rajesh Kumar",
  "Rakesh Kumar",
  "Ramkumar Singh",
  "Ranbeer Kaur",
  "Rachit Arya",
  "Rohit Kumar Tiwari",
  "Sahil Gupta",
  "Sahil Kapoor",
  "Sahiba",
  "Savir Khan",
  "Shri Kant",
  "Siddhartha Kumar",
  "Sidhant Oberai",
  "Sidhant Prajapati",
  "Sukhjinder Pal Singh",
  "Sumit Kushwaha",
  "Sunil Kukkar",
  "Surbhi Chugh",
  "Sushil Kumar",
  "Vageesh Bhardwaj",
  "Vaibhav Mishra",
  "Varun Budhiraja",
  "Vaseem Khan",
];

export const Reportinglist = [
  "Abhay Pratap Singh",
  "Abhayjit Sekhon",
  "Amarjeet Singh",
  "Arwinder Singh",
  "Ashwani Kumar",
  "Bachan Pal",
  "Harpeet Singh",
  "Harsimran",
  "J P Sharma",
  "Manish CS Lange",
  "Manjit Singh Chowhan",
  "Mayank Prasad",
  "Nikhil Sharma",
  "PS Brar",
  "Priya Sharma",
  "Purnendu Kumar",
  "Raj Bahadur Singh",
  "Rajeev Kanda",
  "Rajeev Kumar Singh",
  "Rajeev Pal Singh",
  "Sahil Gupta",
  "Sahil Kapoor",
  "Savir Khan",
  "Siddhartha Kumar",
  "Sukhjinder Pal Singh",
  "Sumit Kushwaha",
  "Sunil Kukkar",
  "Surbhi Chugh",
  "Sushil Kumar",
  "Varun Budhiraja",
  "Vaseem Khan",
];

export const modelNoOptions = ["AT"];
export const brandOptions = ["Promark", "White Label"];
export const dispatchFromOptions = [
  "Patna",
  "Bareilly",
  "Ranchi",
  "Morinda",
  "Lucknow",
  "Delhi",
];
