export const productOptions = {
  Others: {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  IFPD: {
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch", "110 inch"],
    specs: [
      "Android 9, 4GB RAM, 32GB ROM",
      "Android 8, 4GB RAM, 32GB ROM",
      "Android 11, 4GB RAM, 32GB ROM",
      "Android 11, 8GB RAM, 128GB ROM",
      "Android 13, 4GB RAM, 32GB ROM",
      "Android 13, 8GB RAM, 128GB ROM",
      "Android 13, 8GB RAM, 128GB ROM  Inbuilt Camera",
      "Android 14, 8GB RAM, 128GB ROM",
      "Android 14, 8GB RAM, 128GB ROM Inbuilt Camera",
    ],
  },
  OPS: {
    sizes: ["N/A"],
    specs: [
      // i5 6th Gen
      "i5 4TH GEN, 8GB RAM, 256GB ROM",
      "i5 6th Gen, 8GB RAM, 256GB ROM",
      "i5 6th Gen, 8GB RAM, 512GB ROM",
      "i5 6th Gen, 8GB RAM, 1TB ROM",
      "i5 6th Gen, 16GB RAM, 256GB ROM",
      "i5 6th Gen, 16GB RAM, 512GB ROM",
      "i5 6th Gen, 16GB RAM, 1TB ROM",

      // i5 7th Gen
      "i5 7th Gen, 8GB RAM, 256GB ROM",
      "i5 7th Gen, 8GB RAM, 512GB ROM",
      "i5 7th Gen, 8GB RAM, 1TB ROM",
      "i5 7th Gen, 16GB RAM, 256GB ROM",
      "i5 7th Gen, 16GB RAM, 512GB ROM",
      "i5 7th Gen, 16GB RAM, 1TB ROM",

      // i5 8th Gen
      "i5 8th Gen, 8GB RAM, 256GB ROM",
      "i5 8th Gen, 8GB RAM, 512GB ROM",
      "i5 8th Gen, 8GB RAM, 1TB ROM",
      "i5 8th Gen, 16GB RAM, 256GB ROM",
      "i5 8th Gen, 16GB RAM, 512GB ROM",
      "i5 8th Gen, 16GB RAM, 1TB ROM",

      // i5 11th Gen
      "i5 11th Gen, 8GB RAM, 256GB ROM",
      "i5 11th Gen, 8GB RAM, 512GB ROM",
      "i5 11th Gen, 8GB RAM, 1TB ROM",
      "i5 11th Gen, 16GB RAM, 256GB ROM",
      "i5 11th Gen, 16GB RAM, 512GB ROM",
      "i5 11th Gen, 16GB RAM, 1TB ROM",

      // i5 12th Gen
      "i5 12th Gen, 8GB RAM, 256GB ROM",
      "i5 12th Gen, 8GB RAM, 512GB ROM",
      "i5 12th Gen, 8GB RAM, 1TB ROM",
      "i5 12th Gen, 16GB RAM, 256GB ROM",
      "i5 12th Gen, 16GB RAM, 512GB ROM",
      "i5 12th Gen, 16GB RAM, 1TB ROM",

      // i7 4th Gen
      "i7 4th Gen, 8GB RAM, 256GB ROM",
      "i7 4th Gen, 8GB RAM, 512GB ROM",
      "i7 4th Gen, 8GB RAM, 1TB ROM",
      "i7 4th Gen, 16GB RAM, 256GB ROM",
      "i7 4th Gen, 16GB RAM, 512GB ROM",
      "i7 4th Gen, 16GB RAM, 1TB ROM",

      // i7 5th Gen
      "i7 5th Gen, 8GB RAM, 256GB ROM",
      "i7 5th Gen, 8GB RAM, 512GB ROM",
      "i7 5th Gen, 8GB RAM, 1TB ROM",
      "i7 5th Gen, 16GB RAM, 256GB ROM",
      "i7 5th Gen, 16GB RAM, 512GB ROM",
      "i7 5th Gen, 16GB RAM, 1TB ROM",

      // i7 6th Gen
      "i7 6th Gen, 8GB RAM, 256GB ROM",
      "i7 6th Gen, 8GB RAM, 512GB ROM",
      "i7 6th Gen, 8GB RAM, 1TB ROM",
      "i7 6th Gen, 16GB RAM, 256GB ROM",
      "i7 6th Gen, 16GB RAM, 512GB ROM",
      "i7 6th Gen, 16GB RAM, 1TB ROM",

      // i7 7th Gen
      "i7 7th Gen, 8GB RAM, 256GB ROM",
      "i7 7th Gen, 8GB RAM, 512GB ROM",
      "i7 7th Gen, 8GB RAM, 1TB ROM",
      "i7 7th Gen, 16GB RAM, 256GB ROM",
      "i7 7th Gen, 16GB RAM, 512GB ROM",
      "i7 7th Gen, 16GB RAM, 1TB ROM",

      // i7 8th Gen
      "i7 8th Gen, 8GB RAM, 256GB ROM",
      "i7 8th Gen, 8GB RAM, 512GB ROM",
      "i7 8th Gen, 8GB RAM, 1TB ROM",
      "i7 8th Gen, 16GB RAM, 256GB ROM",
      "i7 8th Gen, 16GB RAM, 512GB ROM",
      "i7 8th Gen, 16GB RAM, 1TB ROM",

      // i7 9th Gen
      "i7 9th Gen, 8GB RAM, 256GB ROM",
      "i7 9th Gen, 8GB RAM, 512GB ROM",
      "i7 9th Gen, 8GB RAM, 1TB ROM",
      "i7 9th Gen, 16GB RAM, 256GB ROM",
      "i7 9th Gen, 16GB RAM, 512GB ROM",
      "i7 9th Gen, 16GB RAM, 1TB ROM",

      // i7 10th Gen
      "i7 10th Gen, 8GB RAM, 256GB ROM",
      "i7 10th Gen, 8GB RAM, 512GB ROM",
      "i7 10th Gen, 8GB RAM, 1TB ROM",
      "i7 10th Gen, 16GB RAM, 256GB ROM",
      "i7 10th Gen, 16GB RAM, 512GB ROM",
      "i7 10th Gen, 16GB RAM, 1TB ROM",

      // i7 11th Gen
      "i7 11th Gen, 8GB RAM, 256GB ROM",
      "i7 11th Gen, 8GB RAM, 512GB ROM",
      "i7 11th Gen, 8GB RAM, 1TB ROM",
      "i7 11th Gen, 16GB RAM, 256GB ROM",
      "i7 11th Gen, 16GB RAM, 512GB ROM",
      "i7 11th Gen, 16GB RAM, 1TB ROM",

      // i7 12th Gen
      "i7 12th Gen, 8GB RAM, 256GB ROM",
      "i7 12th Gen, 8GB RAM, 512GB ROM",
      "i7 12th Gen, 8GB RAM, 1TB ROM",
      "i7 12th Gen, 16GB RAM, 256GB ROM",
      "i7 12th Gen, 16GB RAM, 512GB ROM",
      "i7 12th Gen, 16GB RAM, 1TB ROM",
    ],
  },

  "Digital Podium": {
    sizes: [
      "Standard",
      "Standard, RAM 4 GB, ROM 128 GB, Processor i5",
      "Standard, RAM 4 GB, ROM 128 GB, Processor i7",
      "Standard, RAM 4 GB, ROM 256 GB, Processor i5",
      "Standard, RAM 4 GB, ROM 256 GB, Processor i7",
      "Standard, RAM 4 GB, ROM 512 GB, Processor i5",
      "Standard, RAM 4 GB, ROM 512 GB, Processor i7",
      "Standard, RAM 4 GB, ROM 1024 GB, Processor i5",
      "Standard, RAM 4 GB, ROM 1024 GB, Processor i7",
      "Standard, RAM 8 GB, ROM 128 GB, Processor i5",
      "Standard, RAM 8 GB, ROM 128 GB, Processor i7",
      "Standard, RAM 8 GB, ROM 256 GB, Processor i5",
      "Standard, RAM 8 GB, ROM 256 GB, Processor i7",
      "Standard, RAM 8 GB, ROM 512 GB, Processor i5",
      "Standard, RAM 8 GB, ROM 512 GB, Processor i7",
      "Standard, RAM 8 GB, ROM 1024 GB, Processor i5",
      "Standard, RAM 8 GB, ROM 1024 GB, Processor i7",
      "Standard, RAM 16 GB, ROM 128 GB, Processor i5",
      "Standard, RAM 16 GB, ROM 128 GB, Processor i7",
      "Standard, RAM 16 GB, ROM 256 GB, Processor i5",
      "Standard, RAM 16 GB, ROM 256 GB, Processor i7",
      "Standard, RAM 16 GB, ROM 512 GB, Processor i5",
      "Standard, RAM 16 GB, ROM 512 GB, Processor i7",
      "Standard, RAM 16 GB, ROM 1024 GB, Processor i5",
      "Standard, RAM 16 GB, ROM 1024 GB, Processor i7",
    ],
    specs: [
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 2 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
    ],
  },
  "Advance Digital Podium": {
    sizes: [
      "Standard",
      "Front Display 32inch, RAM 4 GB, ROM 128 GB, Processor i5",
      "Front Display 32inch, RAM 4 GB, ROM 128 GB, Processor i7",
      "Front Display 32inch, RAM 4 GB, ROM 256 GB, Processor i5",
      "Front Display 32inch, RAM 4 GB, ROM 256 GB, Processor i7",
      "Front Display 32inch, RAM 4 GB, ROM 512 GB, Processor i5",
      "Front Display 32inch, RAM 4 GB, ROM 512 GB, Processor i7",
      "Front Display 32inch, RAM 4 GB, ROM 1024 GB, Processor i5",
      "Front Display 32inch, RAM 4 GB, ROM 1024 GB, Processor i7",
      "Front Display 32inch, RAM 8 GB, ROM 128 GB, Processor i5",
      "Front Display 32inch, RAM 8 GB, ROM 128 GB, Processor i7",
      "Front Display 32inch, RAM 8 GB, ROM 256 GB, Processor i5",
      "Front Display 32inch, RAM 8 GB, ROM 256 GB, Processor i7",
      "Front Display 32inch, RAM 8 GB, ROM 512 GB, Processor i5",
      "Front Display 32inch, RAM 8 GB, ROM 512 GB, Processor i7",
      "Front Display 32inch, RAM 8 GB, ROM 1024 GB, Processor i5",
      "Front Display 32inch, RAM 8 GB, ROM 1024 GB, Processor i7",
      "Front Display 32inch, RAM 16 GB, ROM 128 GB, Processor i5",
      "Front Display 32inch, RAM 16 GB, ROM 128 GB, Processor i7",
      "Front Display 32inch, RAM 16 GB, ROM 256 GB, Processor i5",
      "Front Display 32inch, RAM 16 GB, ROM 256 GB, Processor i7",
      "Front Display 32inch, RAM 16 GB, ROM 512 GB, Processor i5",
      "Front Display 32inch, RAM 16 GB, ROM 512 GB, Processor i7",
      "Front Display 32inch, RAM 16 GB, ROM 1024 GB, Processor i5",
      "Front Display 32inch, RAM 16 GB, ROM 1024 GB, Processor i7",
    ],
    specs: [
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 2 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
    ],
  },
  "Audio Podium": { sizes: ["Full"], specs: ["N/A"] },
  Kiosk: {
    sizes: ["32 inch", "43 inch", "55 inch", "65 inch"],
    specs: ["Touch Andriod 13/4/32", "Non-Touch Andriod 13/4/32"],
  },
  "PTZ Camera": {
    sizes: ["N/A"],
    specs: [
      "Non-Voice Tracking-Full HD",

      "FHD Voice Tracking",
      "4K Auto Tracking",
      "4K Gesture Tracking",
    ],
  },
  "Document Camera": {
    sizes: ["N/A"],
    specs: [
      "Hydraulic Wall Mount Visualizer",
      "Non-Hydraulic Wall Mount Visualizer",
      "Slim Portable Visualizer",
      "Table Top Portable Visualizer",
      "Visualizer",
    ],
  },
  UPS: {
    sizes: ["Standard"],
    specs: [
      "1 KVA",
      "2 KVA",
      "3 KVA",
      "4 KVA",
      "5 KVA",
      "6 KVA",
      "7 KVA",
      "8 KVA",
      "9 KVA",
      "10 KVA",
      "Offline UPS",
      "Online UPS",
    ],
  },
  "Wallmount Kit": {
    sizes: ["55 inch", "65 inch", "75 inch", "86 inch", "98 inch"],
    specs: ["Standard"],
  },
  "Stylus Pen": { sizes: ["N/A"], specs: ["N/A"] },
  "Sliding Shutter": {
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch"],
    specs: [
      "Common",
      "White & Red Dispaly Boards",
      "White & Green Dispaly Boards",
      "White & Blue Dispaly Boards",
      "N/A",
    ],
  },
  "3 Cup Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  "4 Cup Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  Microphone: {
    sizes: ["N/A"],
    specs: ["Handheld Collar Mic", "Goose Neck Mic", "Collar/Lapel Mic"],
  },
  "Wireless Speaker Phone": {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  CCTV: {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  Keyboard: {
    sizes: ["N/A"],
    specs: ["Wireless", "Wired"],
  },
  "LED Display Controller": {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  "Aluminium Profile Frame for LED Display": {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  "NVR 16 CHANNEL": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "2 MP CAMERA IP CP PLUS": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "BULLET/DOM": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "8 Port POE SWITCH": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "HARD DISK": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  BOX: {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "Cat6e CABLE": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "PVC RACK": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "POWER CABLE": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  RACK: {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "Conduit PIPE": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },

  "White board": {
    sizes: ["3x4", "6x4"],
    specs: ["AS PER SPEC"],
  },
  "FABRIC pin up board": {
    sizes: ["3x4"],
    specs: ["AS PER SPEC"],
  },

  Mouse: {
    sizes: ["N/A"],
    specs: ["Wireless", "Wired"],
  },
  "Interactive White Board": {
    sizes: ["82 inch"],
    specs: ["Ceramic", "Non-Ceramic"],
  },
  "Floor Stand": { sizes: ["N/A"], specs: ["N/A"] },
  "Notice Board": { sizes: ["N/A"], specs: ["N/A"] },
  Visualizer: { sizes: ["N/A"], specs: ["N/A"] },
  "Web Cam": {
    sizes: ["N/A"],
    specs: ["Full HD Non-AI Featured", "4K AI Featured", "4K Auto Tracking"],
  },
  "Bluetooth Microphone": { sizes: ["N/A"], specs: ["N/A"] },
  "UPS Cabinet": { sizes: ["N/A"], specs: ["N/A"] },
  "SD Card": {
    sizes: ["N/A"],
    specs: ["8GB", "16GB", "32GB", "64GB", "128GB"],
  },
  Casing: { sizes: ["N/A"], specs: ["N/A"] },
  "Fitting Accessories": { sizes: ["N/A"], specs: ["N/A"] },
  "HDMI Cable": {
    sizes: ["N/A"],
    specs: ["Standard", "4K"],
  },
  "White Board": {
    sizes: ["2x3", "3x4", "4x6", "4x5", "4x8", "4x10"],
    specs: ["Non-Magnetic", "Magnetic", "RC Magnetic", "UM", "UG"],
  },
  "C-type Cable": { sizes: ["N/A"], specs: ["N/A"] },
  "Fujifilm-Printer": {
    sizes: ["N/A"],
    specs: [
      "Color Printer",
      "Monochrome Printer",
      "Black and White Printer",
      "Multifunction Color Printer",
      "Multifunction Monochrome Printer",
      "Multifunction Black and White Printer",
    ],
  },
  "Google TV": {
    sizes: ["43 inch", "50 inch", "55 inch"],
    specs: ["4GB RAM / 32GB ROM 4K"],
  },
  "Wriety Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Ceiling Mount Kit": {
    sizes: ["Standard"],
    specs: ["Projector Ceiling Mount", "PTZ Ceiling Mount"],
  },
  "Almirah Type Shutter": {
    sizes: ["65 inch", "75 inch", "86 inch", "98  inch"],
    specs: ["Plain", "White Boards", "Green Boards"],
  },
  Aicharya: {
    sizes: ["N/A"],
    specs: ["Standard"],
  },
  TripodStand: {
    sizes: ["N/A"],
    specs: ["Standard"],
  },
  Logo: { sizes: ["N/A"], specs: ["N/A"] },
  Microphones: { sizes: ["N/A"], specs: ["N/A"] },
  "E-Share License": { sizes: ["N/A"], specs: ["N/A"] },
  "PRO Share Software": { sizes: ["N/A"], specs: ["N/A"] },
  "E Share Software": { sizes: ["N/A"], specs: ["N/A"] },
  "DMS Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Battery Bank": { sizes: ["N/A"], specs: ["N/A"] },
  "Rack & Interlink": { sizes: ["N/A"], specs: ["N/A"] },
  "Green Board": {
    sizes: ["2x3", "3x4", "4x6", "4x5", "4x8", "4x10"],
    specs: ["Non-Magnetic", "Magnetic", "RC Magnetic", "UM", "UG"],
  },
  "Wooden Podium": { sizes: ["N/A"], specs: ["N/A"] },
  "Writing Board": {
    sizes: ["4X8", "4X10", "4X12"],
    specifications: ["Green", "White"],
  },
  "LED Video Wall": { sizes: ["N/A"], specs: ["N/A"] },
  "4K Video Bar": { sizes: ["N/A"], specs: ["N/A"] },
  "Microsoft Office 2016 Licensed": { sizes: ["N/A"], specs: ["N/A"] },
  "Windows 11 Licensed": { sizes: ["N/A"], specs: ["N/A"] },
  "Embibe Content": { sizes: ["N/A"], specs: ["N/A"] },
  SSD: {
    sizes: ["N/A"],
    specs: ["256GB", "512GB", "1TB"],
  },
  RAM: {
    sizes: ["N/A"],
    specs: ["8GB", "16GB"],
  },
  "Video Conferencing Camera": { sizes: ["N/A"], specs: ["N/A"] },
  Speaker: { sizes: ["75", "65", "86"], specs: ["RSP "] },
  "CBSE Content": { sizes: ["N/A"], specs: ["N/A"] },
  "ICSE Content": { sizes: ["N/A"], specs: ["N/A"] },
  "PA System Speakers": { sizes: ["N/A"], specs: ["N/A"] },
  "Red Board": { sizes: ["N/A"], specs: ["N/A"] },
  "Promark Stickers": { sizes: ["N/A"], specs: ["N/A"] },
  "Bluetooth Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  "3 Cup Conference Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  "Conference Setup-Delegate Room": { sizes: ["N/A"], specs: ["N/A"] },
  Content: { sizes: ["N/A"], specs: ["N/A"] },
  Flex: { sizes: ["N/A"], specs: ["N/A"] },
  "Wireless Speakerphone - Two Pair": { sizes: ["N/A"], specs: ["N/A"] },
  Remote: { sizes: ["N/A"], specs: ["N/A"] },
  "Educational Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Hydraulic Bracket": { sizes: ["N/A"], specs: ["N/A"] },
  "Desktop PC Monitor": { sizes: ["N/A"], specs: ["N/A"] },
  "Home Theatre": { sizes: ["N/A"], specs: ["N/A"] },
  "Digital Audio Processor": { sizes: ["N/A"], specs: ["N/A"] },
  Projector: {
    sizes: ["N/A"],
    specs: ["Long Throw", "Short Throw", "Ultra Long Throw"],
  },
  "LED TV": {
    sizes: ["32 inch", "43 inch", "55 inch", "65 inch"],
    specs: ["N/A"],
  },
  "Digital Podium Controller": { sizes: ["N/A"], specs: ["N/A"] },
  "Amplifier Mic Receiver": { sizes: ["N/A"], specs: ["N/A"] },
  "Wireless Mic Receiver": { sizes: ["N/A"], specs: ["N/A"] },
  "Projector Screen": { sizes: ["N/A"], specs: ["N/A"] },
  Speakerphone: { sizes: ["N/A"], specs: ["N/A"] },

  "Bubble Roll": { sizes: ["N/A"], specs: ["N/A"] },
  "Wrapping Roll": { sizes: ["N/A"], specs: ["N/A"] },
  "Powered Active Speaker": {
    sizes: ["N/A"],
    specs: [
      'Drive Unit: 15" bass × 1, 1.75" tweeter × 1, Frequency Response: 45 Hz – 18,000 Hz, Speaker Sensitivity: 98 ± 2 dB, Max. SPL: 125 ± 2 dB, Active Signal Input Impedance: 20 kΩ, Amplifier Power: 1500 W Class-D, Speaker Continuous Power: 450 W (AES), Directivity (H × V): 90° × 60°, Amplifier Distortion: < 0.05%, Damping Coefficient: > 250, Working Voltage: AC 220V / 50Hz',
    ],
  },
  "16 Channel Audio Mixer": {
    sizes: ["N/A"],
    specs: [
      "Nos of Audio Channel: 16, Frequency Response: +0.5dB/-1.5dB (20Hz to 48kHz) @1kHz GAIN: Min, Total Harmonic Distortion: 0.03% @ +14dBu (20Hz–20kHz) GAIN: Min, 0.005% @ +24dBu (1kHz) GAIN: Min, Hum and Noise (20Hz–20kHz): Input Noise: -128dBu (Mono in, Rs: 150Ω, GAIN Max), Residual Output Noise: -102dBu (STEREO OUT, Fader Min), Crosstalk (1kHz): -78dB, Output Channels: STEREO OUT: 2, MONITOR OUT: 1, PHONES: 1, Channel Gain Controls: 4, 3-Band EQ: Yes, Bus Configuration: Stereo: 1, Grouping: 4, AUX: 4, PAD (Mono Input): 26dB, High-Pass Filter (HPF): 80Hz, 12dB/oct (Mono & Stereo MIC inputs), Compressor (Mono Input): Threshold: +22dBu to -8dBu, Ratio: 1:1 to 4:1, Output Level: 0 to 7dB, Attack: 25ms, Release: 300ms, EQ (High): ±15dB @ 10kHz, EQ (Mid): Mono: ±15dB, 250Hz–5kHz peak, Stereo: ±15dB @ 2.5kHz peak, EQ (Low): ±15dB @ 100Hz, Peak LED (Mono): Lights at 3dB below clipping, Digital Effects: Yes, USB Audio Interface: Yes, Phantom Power: +48V, Power Supply Voltage: AC100–240V, 50/60Hz, Power Consumption: 30W, Included Accessories: Technical specifications, AC power cord, Cabinet mounting kit, Operating Temperature Range: 0 to +40°C, Equivalent Noise Level: 26 dB(A)",
    ],
  },
  "Gooseneck Mic": {
    sizes: ["18 inch"],
    specs: [
      "Adjustment Range (Transmitter): 0 to -30 dB (adjustable in 10 dB steps), Polar Pattern: Omnidirectional, Total Harmonic Distortion (THD): ≤ 0.9%, Audio Frequency Response: 50 to 16,000 Hz (–3 dB), Mic Level: 10 dB, Signal-to-Noise Ratio: ≥ 103 dBA, Squelch: Adjustable from 3 dBμV to 28 dBμV (with pilot tone), Operating Temperature: -10°C to +40°C, Effective Range: Up to 300 m (open environment)",
    ],
  },
  "Wireless Microphone": {
    sizes: ["N/A"],
    specs: [
      "Transmitter: 2 Handheld, Frequency Range: 632 – 661.25 MHz, Number of Channels: 48, Frequency Step: 250 KHz, Dynamic Range: 82 dB, Max. Frequency Deviation: ±45 KHz, Audio Response: 120 Hz – 15 KHz (±3 dB), Comprehensive S/N Ratio: >70 dB, Comprehensive Distortion: ≤1%, Operating Temperature: -10°C to +40°C, Effective Range: Up to 300 m (open environment)",
    ],
  },
  "Wired Vocal Microphone": {
    sizes: ["N/A"],
    specs: [
      "Warranty: 10 years (AMER), Polar Pattern: Cardioid, Frequency Response: 40 - 16,000 Hz, Connection: Wired, Connectors: 3-pin XLR, Operating Temperature: 0°C to 40°C, Nominal Impedance: 350 Ω, Min. Terminating Impedance: 1000 Ω",
    ],
  },
  "Microphone Stand": {
    sizes: ["N/A"],
    specs: [
      "Type: Floor Stand, Height: 690-1000mm, Base Dia: 230mm, Weight: Not Less Than 3Kg",
    ],
  },
  "Microphone Cable": {
    sizes: ["N/A"],
    specs: [
      "No. of Conductors: 2, Conductor: 25/0.10 mm, Cross-Sectional Area: 0.22 sq.mm (24 AWG), Insulation Material: HDPE, Insulation OD: 1.10 mm, Insulation Colours: Red / Yellow, Shield Conductor: ATC Copper – (0.10mm) 65 wires (approx), Shield Type: Serve Shield + Aluminum Foil + Mylar Tape, Jacket Material: High Flex Matt Finish PVC, Jacket OD: 4.00 mm ± 0.10mm",
    ],
  },

  "Desktop Computer": {
    sizes: ["24 inch Monitor"],
    specs: [
      "Processor: i5 12th Gen, RAM: 16GB, Storage: 512GB SSD, OS: Windows 11, Software: Office 2021, Features: Inbuilt WiFi, Keyboard, Mouse",
    ],
  },
  "Printer With Scanner All In One": {
    sizes: ["N/A"],
    specs: [
      "Type: Image CLASS 4 In 1 Multifunctional Printer, Features: Monochrome Laser, Network, Duplex, ADF",
    ],
  },
};

export const statesAndCities = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Jaganathpuram",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Kurnool",
    "Rajahmundry",
    "Nellore",
    "Anantapur",
    "Kadapa",
    "Srikakulam",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Proddatur",
    "Machilipatnam",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Tawang",
    "Ziro",
    "Pasighat",
    "Bomdila",
    "Naharlagun",
    "Roing",
    "Aalo",
    "Tezu",
    "Changlang",
    "Khonsa",
    "Yingkiong",
    "Daporijo",
    "Seppa",
  ],
  Assam: [
    "Agartala",
    "Tripura",
    "Guwahati",
    "Dibrugarh",
    "Jorhat",
    "Silchar",
    "Tezpur",
    "Tinsukia",
    "Nagaon",
    "Sivasagar",
    "Barpeta",
    "Goalpara",
    "Karimganj",
    "Lakhimpur",
    "Diphu",
    "Golaghat",
    "Kamrup",
  ],
  Bihar: [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Buxar",
    "Darbhanga",
    "East Champaran",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Khagaria",
    "Kishanganj",
    "Kaimur",
    "Katihar",
    "Lakhisarai",
    "Madhubani",
    "Munger",
    "Madhepura",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnia",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    "Sheohar",
    "Sheikhpura",
    "Saran",
    "Sitamarhi",
    "Supaul",
    "Siwan",
    "Vaishali",
    "West Champaran",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Korba",
    "Bhilai",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Dhamtari",
    "Kawardha",
    "Mahasamund",
    "Kondagaon",
    "Bijapur",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Sanguem",
    "Canacona",
    "Quepem",
    "Valpoi",
    "Sanquelim",
    "Curchorem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Morbi",
    "Nadiad",
    "Porbandar",
    "Mehsana",
    "Bharuch",
    "Navsari",
    "Surendranagar",
  ],
  Haryana: [
    "Bahadurgarh",
    "Charkhi Dadri",
    "Panchkula",
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Hisar",
    "Rohtak",
    "Karnal",
    "Bhiwani",
    "Kaithal",
    "Kurukshetra",
    "Sonipat",
    "Jhajjar",
    "Jind",
    "Fatehabad",
    "Pehowa",
    "Pinjore",
    "Rewari",
    "Yamunanagar",
    "Sirsa",
    "Dabwali",
    "Narwana",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul and Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una",
  ],
  Jharkhand: [
    "Ranchi",
    "Koderma",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Palamu",
    "Gumla",
    "Lohardaga",
    "Dumka",
    "Chatra",
    "Pakur",
    "Jamtara",
    "Simdega",
    "Sahibganj",
    "Godda",
    "Latehar",
    "Khunti",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Kalaburagi",
    "Ballari",
    "Davangere",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Vijayapura",
    "Chikkamagaluru",
    "Hassan",
    "Mandya",
    "Raichur",
    "Bidar",
    "Bagalkot",
    "Chitradurga",
    "Kolar",
    "Gadag",
    "Yadgir",
    "Haveri",
    "Dharwad",
    "Ramanagara",
    "Chikkaballapur",
    "Kodagu",
    "Koppal",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kannur",
    "Alappuzha",
    "Thrissur",
    "Kottayam",
    "Palakkad",
    "Ernakulam",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Kollam",
    "Kasaragod",
    "Punalur",
    "Varkala",
    "Changanassery",
    "Kayani",
    "Kizhakkambalam",
    "Perumbavoor",
    "Muvattupuzha",
    "Attingal",
    "Vypin",
    "North Paravur",
    "Adoor",
    "Cherthala",
    "Mattancherry",
    "Fort Kochi",
    "Munroe Island",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Ratlam",
    "Satna",
    "Dewas",
    "Murwara (Katni)",
    "Chhindwara",
    "Rewa",
    "Burhanpur",
    "Khandwa",
    "Bhind",
    "Shivpuri",
    "Vidisha",
    "Sehore",
    "Hoshangabad",
    "Itarsi",
    "Neemuch",
    "Chhatarpur",
    "Betul",
    "Mandsaur",
    "Damoh",
    "Singrauli",
    "Guna",
    "Ashok Nagar",
    "Datia",
    "Mhow",
    "Pithampur",
    "Shahdol",
    "Seoni",
    "Mandla",
    "Tikamgarh",
    "Raisen",
    "Narsinghpur",
    "Morena",
    "Barwani",
    "Rajgarh",
    "Khargone",
    "Anuppur",
    "Umaria",
    "Dindori",
    "Sheopur",
    "Alirajpur",
    "Jhabua",
    "Sidhi",
    "Harda",
    "Balaghat",
    "Agar Malwa",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Thane",
    "Satara",
    "Latur",
    "Chandrapur",
    "Jalgaon",
    "Bhiwandi",
    "Shirdi",
    "Akola",
    "Parbhani",
    "Raigad",
    "Washim",
    "Buldhana",
    "Nanded",
    "Yavatmal",
    "Beed",
    "Amravati",
    "Kalyan",
    "Dombivli",
    "Ulhasnagar",
    "Nagothane",
    "Vasai",
    "Virar",
    "Mira-Bhayandar",
    "Dhule",
    "Sangli",
    "Wardha",
    "Ahmednagar",
    "Pandharpur",
    "Malegaon",
    "Osmanabad",
    "Gondia",
    "Baramati",
    "Jalna",
    "Hingoli",
    "Sindhudurg",
    "Ratnagiri",
    "Palghar",
    "Ambarnath",
    "Badlapur",
    "Taloja",
    "Alibaug",
    "Murbad",
    "Karjat",
    "Pen",
    "Newasa",
  ],
  Manipur: [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Bishnupur",
    "Kakching",
    "Senapati",
    "Ukhrul",
    "Tamenglong",
    "Jiribam",
    "Moreh",
    "Noney",
    "Pherzawl",
    "Kangpokpi",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Cherrapunjee",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Mawkyrwat",
    "Resubelpara",
    "Mairang",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Saiha",
    "Lawngtlai",
    "Mamit",
    "Hnahthial",
    "Khawzawl",
    "Saitual",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Mon",
    "Zunheboto",
    "Phek",
    "Longleng",
    "Kiphire",
    "Peren",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Puri",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Jeypore",
    "Angul",
    "Dhenkanal",
    "Keonjhar",
    "Kendrapara",
    "Jagatsinghpur",
    "Paradeep",
    "Bargarh",
    "Rayagada",
    "Koraput",
    "Nabarangpur",
    "Kalahandi",
    "Nuapada",
    "Phulbani",
    "Balangir",
    "Sundargarh",
  ],
  Punjab: [
    "Amritsar",
    "Bathinda",
    "Barnala",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Ferozepur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "S.A.S. Nagar", // Sahibzada Ajit Singh Nagar
    "Sangrur",
    "Shaheed Bhagat Singh Nagar", // Nawanshahr
    "Sri Muktsar Sahib",
    "Tarn Taran",
  ],
  Rajasthan: [
    "Baran",
    "Newai",
    "Gaganagar",
    "Suratgarh",
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Kota",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Nagaur",
    "Jhunjhunu",
    "Chittorgarh",
    "Tonk",
    "Barmer",
    "Jaisalmer",
    "Dholpur",
    "Bhilwara",
    "Hanumangarh",
    "Sawai Madhopur",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Pelling",
    "Geyzing",
    "Mangan",
    "Rangpo",
    "Jorethang",
    "Yuksom",
    "Ravangla",
    "Lachen",
    "Lachung",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thanjavur",
    "Tuticorin",
    "Dindigul",
    "Cuddalore",
    "Kancheepuram",
    "Nagercoil",
    "Kumbakonam",
    "Karur",
    "Sivakasi",
    "Namakkal",
    "Tiruppur",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Ramagundam",
    "Siddipet",
    "Adilabad",
    "Nalgonda",
    "Mancherial",
    "Kothagudem",
    "Zaheerabad",
    "Miryalaguda",
    "Bhongir",
    "Jagtial",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Kamalpur",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Sonamura",
    "Melaghar",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahar",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kushi Nagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffar Nagar",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharth Nagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Rishikesh",
    "Mussoorie",
    "Almora",
    "Pithoragarh",
    "Haldwani",
    "Rudrapur",
    "Bageshwar",
    "Champawat",
    "Uttarkashi",
    "Roorkee",
    "Tehri",
    "Lansdowne",
  ],
  "West Bengal": [
    "Kolkata",
    "Garia",
    "Darjeeling",
    "Siliguri",
    "Howrah",
    "Asansol",
    "Durgapur",
    "Malda",
    "Cooch Behar",
    "Haldia",
    "Kharagpur",
    "Raiganj",
    "Bardhaman",
    "Jalpaiguri",
    "Chandannagar",
    "Kalimpong",
    "Alipurduar",
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Havelock Island",
    "Diglipur",
    "Neil Island",
    "Car Nicobar",
    "Little Andaman",
    "Long Island",
    "Mayabunder",
    "Campbell Bay",
    "Rangat",
    "Wandoor",
  ],
  Chandigarh: [
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 7",
    "Sector 8",
    "Sector 9",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Amli",
    "Kachigam",
    "Naroli",
    "Vapi",
    "Marwad",
    "Samarvarni",
    "Kawant",
  ],
  Delhi: [
    "New Delhi",
    "Rani Bagh",
    "Shalimar Bagh",
    "Tilak Nagar",
    "Hari Nagar Dadb",
    "Hari Nagar",
    "Maya Puri",
    "Alaknanda",
    "Old Delhi",
    "Dwarka",
    "Rohini",
    "Karol Bagh",
    "Lajpat Nagar",
    "Saket",
    "Vasant Kunj",
    "Janakpuri",
    "Mayur Vihar",
    "Shahdara",
    "Preet Vihar",
    "Pitampura",
    "Chanakyapuri",
    "Narela",
    "Mehrauli",
    "Najafgarh",
    "Okhla",
    "Tilak Nagar",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],
  Ladakh: [
    "Leh",
    "Kargil",
    "Diskit",
    "Padum",
    "Nubra",
    "Tangtse",
    "Sankoo",
    "Zanskar",
    "Nyoma",
    "Turtuk",
    "Hanle",
  ],
  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Amini",
    "Andrott",
    "Kalpeni",
    "Kadmat",
    "Chetlat",
    "Bitra",
    "Bangaram",
  ],
  Puducherry: [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam",
    "Villianur",
    "Bahour",
    "Oulgaret",
    "Ariyankuppam",
    "Nettapakkam",
  ],
};

export const orderTypeOptions = [
  "B2G",
  "B2C",
  "B2B",
  "Demo",
  "Replacement",
  "Stock Out",
  "Repair",
];
export const companyOptions = ["Promark", "Foxmate", "Promine", "Primus"];

export const paymentMethodOptions = ["Cash", "NEFT", "RTGS", "Cheque"];
export const paymentTermsOptions = [
  "100% Advance",
  "Partial Advance",
  "Credit",
];
export const salesPersonlist = [
  "Aasim Musadiq",
  "Narinder Singh",
  "Ashish Soni",
  "Ankur Jain",
  "Abhay Pratap Singh",
  "Abhay Bhardwaj",
  "Abhayjit Sekhon",
  "Ajay Kumar",
  "Anu Sethi",
  "Amarjeet Singh",
  "Aniket Singh",
  "Anil Kumar",
  "Animesh Trivedi",
  "Anirban Syam",
  "Ankit Sharma",
  "Anup Panday",
  "Arif Khan",
  "Arwinder Singh",
  "Ashwani Kumar",
  "Awadesh Kumar Srivastav",
  "Bachan Pal",
  "Barjesh Singh",
  "Deepak saini",
  "Parth Bhardwaj",
  "Ekant Yati",
  "Gursewak Singh",
  "Gem Team",
  "Harish Kumar",
  "Heera Singh Daspa",
  "Harpeet Singh",
  "J P Sharma",
  "Jagan Lal",
  "Javvad Akram",
  "Kulwinder Singh",
  "Manish CS Lange",
  "Manjit Singh Chowhan",
  "Mayank Goutam",
  "Mayank Prasad",
  "Monika",
  "Nikhil Sharma",
  "Nadeem Khan",
  "Narinder Singh",
  "Parmjeet Singh",
  "Priyanka Rajput",
  "Pitamber Sharma",
  "Priya Sharma",
  "Pihu Juneja",
  "PS Brar",
  "Purnendu Kumar",
  "Raj Bahadur Singh",
  "Rajeev Kanda",
  "Rajeev Kumar Singh",
  "Rajeev Pal Singh",
  "Rajesh Kumar",
  "Rakesh Kumar",
  "Riya Rana",
  "Ramkumar Singh",
  "Ranbeer Kaur",
  "Rachit Arya",
  "Rohit Kumar Tiwari",
  "Shadab Khan",
  "Sahil Gupta",
  "Sahil Kapoor",
  "Sahiba",
  "Savir Khan",
  "Shri Kant",
  "Siddhartha Kumar",
  "Sidhant Oberai",
  "Sidhant Prajapati",
  "Sukhjinder Pal Singh",
  "Sumit Kushwaha",
  "Sunil Kukkar",
  "Surbhi Chugh",
  "Sushil Kumar",
  "Vinay Bhardwaj",
  "Vageesh Bhardwaj",
  "Vaibhav Mishra",
  "Varun Budhiraja",
  "Vaseem Khan",
];

export const Reportinglist = [
  "Abhay Pratap Singh",
  "Abhayjit Sekhon",
  "Amarjeet Singh",
  "Arwinder Singh",
  "Ashwani Kumar",
  "Bachan Pal",
  "Ekant Yati",
  "Gem Team",
  "Heera Singh Daspa",
  "Harpeet Singh",
  "Harsimran",
  "J P Sharma",
  "Manish CS Lange",
  "Manjit Singh Chowhan",
  "Mayank Prasad",
  "Nikhil Sharma",
  "PS Brar",
  "Priya Sharma",
  "Purnendu Kumar",
  "Raj Bahadur Singh",
  "Rajeev Kanda",
  "Rajeev Kumar Singh",
  "Rajeev Pal Singh",
  "Sahil Gupta",
  "Sahil Kapoor",
  "Savir Khan",
  "Siddhartha Kumar",
  "Sukhjinder Pal Singh",
  "Sumit Kushwaha",
  "Sunil Kukkar",
  "Surbhi Chugh",
  "Sushil Kumar",
  "Varun Budhiraja",
  "Vaseem Khan",
];

export const modelNoOptions = ["AT", "PRO MR PC", "Standard"];
export const brandOptions = ["Promark", "White Label"];
export const dispatchFromOptions = [
  "Patna",
  "Bareilly",
  "Ranchi",
  "Morinda",
  "Lucknow",
  "Delhi",
  "Jaipur",
  "Rajasthan",
];
